// <auto-generated />
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace QRAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Equipment", b =>
                {
                    b.Property<long>("EquipmentTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("equipment_table_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EquipmentTableId"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleName")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("responsible_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("title");

                    b.HasKey("EquipmentTableId")
                        .HasName("equipment_pk");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("DAL.Models.EquipmentPhoto", b =>
                {
                    b.Property<long>("PhotoTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("photo_table_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PhotoTableId"));

                    b.Property<long>("EquipmentFkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("equipment_fk_id");

                    b.Property<string>("Photo")
                        .HasColumnType("character varying")
                        .HasColumnName("photo");

                    b.HasKey("PhotoTableId")
                        .HasName("equipment_photos_pk");

                    b.HasIndex("EquipmentFkId");

                    b.ToTable("equipment_photos", (string)null);
                });

            modelBuilder.Entity("DAL.Models.EquipmentPhoto", b =>
                {
                    b.HasOne("DAL.Models.Equipment", "EquipmentFk")
                        .WithMany("EquipmentPhotos")
                        .HasForeignKey("EquipmentFkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("equipment_photos_fk");

                    b.Navigation("EquipmentFk");
                });

            modelBuilder.Entity("DAL.Models.Equipment", b =>
                {
                    b.Navigation("EquipmentPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
